import React from "react";
import type { Metadata } from "next";
import "@styles/scss/main.scss";
import Header from "@widgets/Header";
import Footer from "@widgets/Footer";

export const metadata: Metadata = {
  title: "NCIPETC-25 | CCET",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="">{children}</div>
      </body>
    </html>
  );
}
